//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketingSystem.DALTicketingSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketingSystemEntities : DbContext
    {
        public TicketingSystemEntities()
            : base("name=TicketingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TTICKET> TTICKET { get; set; }
        public virtual DbSet<TTICKETSTATUS> TTICKETSTATUS { get; set; }
        public virtual DbSet<TUSER> TUSER { get; set; }
    }
}
