//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketingSystem.DALTicketingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTICKET
    {
        public int id { get; set; }
        public string title { get; set; }
        public string status { get; set; }
        public string autor { get; set; }
        public string assignee { get; set; }
        public System.DateTime created { get; set; }
        public string body { get; set; }
    
        public virtual TUSER TUSER { get; set; }
        public virtual TUSER TUSER1 { get; set; }
        public virtual TTICKETSTATUS TTICKETSTATUS { get; set; }
    }
}
